export const slides = [
	{
		id: 1,
		type: "React App",
		title: "React Leaflet",
		img: "/leaflet.png",
		imgsmall: "/geo.png",
		url: "https://dotdev.be/geo",
		gitHubUrl: "https://github.com/tomatoweb/dotdev-next-tw/blob/main/src/components/maps/index.jsx",
		icon: "/react.png",
		description: "React Leaflet in a Next.js application to visualize geographical data. Functional add/remove markers. Prisma ORM",
	},
	{
		id: 2,
		type: "Next.js App",
		title: "Documentation Nextjs",
		img: "/doc-next-tw-mui.png",
		imgsmall: "/doc-next-small.png",
		url: "https://doc.dotdev.be",
		gitHubUrl: "https://github.com/tomatoweb/doc-dotdev-nextjs",
		icon: "/nextjs.svg",
		description: "Next.js Wiki application with Tailwind CSS and MUI Material for documentation purposes. Includes search functionality",
	},
	{
		id: 3,
		type: "Symfony App",
		title: "E-shop with Symfony",
		img: "/symfony-app.png",
		imgsmall: "/symfony-app-small.png",
		url: "https://symfony.dotdev.be",
		gitHubUrl: "https://github.com/tomatoweb/symfony-tailwind",
		icon: "/symfony-black.svg",
		description: "Symfony application with e-commerce solution. Includes product management, cart, and checkout functionalities",
	},
	{
		id: 5,
		type: "Next.js App",
		title: "Dashboard with Nextjs",
		img: "/dashboard-next-mui.png",
		imgsmall: "/dashboard-next-small.png",
		url: "https://dashboard.dotdev.be",
		gitHubUrl: "https://github.com/tomatoweb/dashboard-nextjs",
		icon: "/nextjs.svg",
		description: "Next.js application with MUI Material, Tailwind styled dashboard. Includes user management, analytics, and reporting features",
	},
	{
		id: 4,
		type: "React App",
		title: "Social with Native React",
		img: "/social-react-mui.png",
		imgsmall: "/social-react-small.png",
		url: "https://social.dotdev.be",
		gitHubUrl: "https://github.com/tomatoweb/social-react-mui",
		icon: "/react.png",
		description: "Native React and MUI Material styled social application with user profiles, posts, and comments. Includes authentication",
	},
	{
		id: 7,
		type: "Laravel App",
		title: "E-shop with Laravel",
		img: "/eshop-laravel.png",
		imgsmall: "/eshop-laravel-small.png",
		url: "https://laravel.dotdev.be",
		gitHubUrl: "https://github.com/tomatoweb/laravel-tailwind",
		icon: "/laravel.svg",
		description: "Laravel application with e-commerce solution Tailwind styled. Includes product management, cart, and checkout",
	},
	{
		id: 9,
		type: "Vue.js App",
		title: "Vue.js Quasar",
		img: "/vue-quasar-page.png",
		imgsmall: "/vue-quasar-page.png",
		url: "https://vue.mathiasappelmans.be/form",
		gitHubUrl: "https://github.com/tomatoweb/vue-quasar-app",
		icon: "/vue.svg",
		description: "Vue.js Quasar app with API PHP backend to handle phishing detection. Includes form validation and API integration",
	},
	{
		id: 6,
		type: "Next.js App",
		title: "React e-shop",
		img: "/eshop-next-tw.png",
		imgsmall: "/eshop-next-small.png",
		url: "https://e-shop.dotdev.be",
		gitHubUrl: "https://github.com/tomatoweb/e-shop-next",
		icon: "/nextjs.svg",
		description: "E-commerce application built with Next.js and Tailwind CSS. Features product listings, cart management, and checkout",
	},
	{
		id: 8,
		type: "React App",
		title: "Immo with Native React",
		img: "/immo-react-vite-sass.png",
		imgsmall: "/agency-small.png",
		url: "https://agency.dotdev.be",
		gitHubUrl: "https://github.com/tomatoweb/immo-react-vite",
		icon: "/react.png",
		description: "Immo application built with Native React and Vite. Features property listings, search functionality, and user profiles",
	},
];