export const slides = [
    {
        id: 1,
        title: "React Leaflet",
        img: "/leaflet.png",
        imgsmall: "/geo.png",
        url: "https://dotdev.be/geo",
        icon: "/symfony.svg",
        description: "React Leaflet in a Next.js application to visualize geographical data. Functional add/remove markers. Prisma ORM",
    },
    {
        id: 2,
        title: "E-shop with Symfony",
        img: "/symfony-app.png",
        imgsmall: "/symfony-app-small.png",
        url: "https://symfony.dotdev.be",
        icon: "/symfony.svg",
        description: "Symfony application with e-commerce solution. Includes product management, cart, and checkout functionalities",
    },
    {
        id: 3,
        title: "Social with Native React",
        img: "/social-react-mui.png",
        imgsmall: "/social-react-small.png",
        url: "https://social.dotdev.be",
        icon: "/react-full.png",
        description: "Native React and MUI Material styled social application with user profiles, posts, and comments. Includes authentication",
    },
    {
        id: 4,
        title: "Dashboard with Nextjs",
        img: "/dashboard-next-mui.png",
        imgsmall: "/dashboard-next-small.png",
        url: "https://dashboard.dotdev.be",
        icon: "/symfony.svg",
        description: "Next.js application with MUI Material, Tailwind styled dashboard. Includes user management, analytics, and reporting features",
    },
    {
        id: 5,
        title: "E-shop with Symfony",
        img: "/eshop-next-tw.png",
        imgsmall: "/eshop-next-small.png",
        url: "https://e-shop.dotdev.be",
        icon: "/symfony.svg",
        description: "E-commerce application built with Next.js and Tailwind CSS. Features product listings, cart management, and checkout process",
    },
    {
        id: 6,
        title: "Documentation Nextjs",
        img: "/doc-next-tw-mui.png",
        imgsmall: "/doc-next-small.png",
        url: "https://doc.dotdev.be",
        description: "Next.js application with Tailwind CSS and MUI Material for documentation purposes. Includes search functionality and responsive design",
    },
    {
        id: 7,
        title: "E-shop with Laravel",
        img: "/eshop-laravel.png",
        imgsmall: "/eshop-laravel-small.png",
        url: "https://laravel.dotdev.be",
        description: "Laravel application with e-commerce solution Tailwind styled. Includes product management, cart, and checkout functionalities",
    },
    {
        id: 8,
        title: "Immo with Native React",
        img: "/immo-react-vite-sass.png",
        imgsmall: "/agency-small.png",
        url: "https://agency.dotdev.be",
        icon: "/react-full.png",
        description: "A React Leaflet application to visualize geographical data. Functional add/remove markers. Prisma ORM integration",
    },
    {
        id: 8,
        title: "Vue.js PHP",
        img: "/phishing.png",
        imgsmall: "/phishing.png",
        url: "https://dotdev.be",
        icon: "/phishing.png",
        description: "Vue.js form with API PHP backend to handle phishing detection. Includes form validation and API integration",
    },
];