export const slides = [
    {
        id: 1,
        title: "React Leaflet",
        img: "/leaflet.png",
        imgsmall: "/geo.png",
        url: "https://dotdev.be/geo",
        icon: "/symfony.svg",
    },
    {
        id: 2,
        title: "E-shop with Symfony",
        img: "/symfony-app.png",
        imgsmall: "/symfony-app-small.png",
        url: "https://symfony.dotdev.be",
        icon: "/symfony.svg",
    },
    {
        id: 3,
        title: "Social with Native React",
        img: "/social-react-mui.png",
        imgsmall: "/social-react-small.png",
        url: "https://social.dotdev.be",
        icon: "/react-full.png",
    },
    {
        id: 4,
        title: "Dashboard with Nextjs",
        img: "/dashboard-next-mui.png",
        imgsmall: "/dashboard-next-small.png",
        url: "https://dashboard.dotdev.be",
    },
    {
        id: 5,
        title: "E-shop with Symfony",
        img: "/symfony-app.png",
        imgsmall: "/symfony-app-small.png",
        url: "https://symfony.dotdev.be",
        icon: "/symfony.svg",
    },
    {
        id: 6,
        title: "Documentation Nextjs",
        img: "/dotdev-next-tw-mui.png",
        imgsmall: "/dotdev-next-small.png",
        url: "https://doc.dotdev.be",
    },
    {
        id: 7,
        title: "E-shop with Laravel",
        img: "/eshop-laravel.png",
        imgsmall: "/eshop-laravel-small.png",
        url: "https://laravel.dotdev.be",
    },
    {
        id: 8,
        title: "Immo with Native React",
        img: "/immo-react-vite-sass.png",
        imgsmall: "/agency-small.png",
        url: "https://agency.dotdev.be",
        icon: "/react-full.png",
    },
];